#!/usr/bin/env python3
"""Build a self-contained `llama` binary and package it as a release archive.

Usage:
    python packaging/build.py --version 1.2.3 [--dry-run]

Runs on macOS, Linux, and Windows. PyInstaller does not cross-compile, so this
builds only for the host's OS/arch. Output: dist-release/llama-<ver>-<os>-<arch>.<ext>
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SPEC = PROJECT_ROOT / "packaging" / "llama.spec"
DIST = PROJECT_ROOT / "dist"
DIST_RELEASE = PROJECT_ROOT / "dist-release"
VERSION_FILE = PROJECT_ROOT / "src" / "llama" / "_version.py"
ENTITLEMENTS = PROJECT_ROOT / "packaging" / "llama.entitlements"
METADATA = PROJECT_ROOT / "packaging" / "metadata.json"

TIMESTAMP_URL = "http://timestamp.acs.microsoft.com"
FILE_DIGEST = "SHA256"
SIGNTOOL_FIXED = Path(r"C:\Program Files (x86)\Windows Kits\10\bin\10.0.28000.0\x64\signtool.exe")
SIGNTOOL_KITS_BIN = Path(r"C:\Program Files (x86)\Windows Kits\10\bin")
AZ_WBIN_DIRS = (
    r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin",
    r"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin",
)


def os_slug() -> str:
    if sys.platform == "darwin":
        return "macos"
    if sys.platform.startswith("linux"):
        return "linux"
    if sys.platform == "win32":
        return "windows"
    raise SystemExit(f"unsupported platform: {sys.platform}")


def arch_slug() -> str:
    m = platform.machine().lower()
    if m in ("x86_64", "amd64"):
        return "x86_64"
    if m in ("arm64", "aarch64"):
        return "arm64"
    raise SystemExit(f"unsupported arch: {platform.machine()}")


def exe_name() -> str:
    return "llama.exe" if sys.platform == "win32" else "llama"


def write_version_file(version: str) -> None:
    VERSION_FILE.write_text(
        f'"""Generated by packaging/build.py — do not edit or commit."""\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


def run_pyinstaller(version: str) -> None:
    env = {**os.environ, "LLAMA_VERSION": version}
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", str(SPEC), "--clean", "--noconfirm"],
        cwd=PROJECT_ROOT,
        env=env,
        check=True,
    )


def smoke_test(version: str) -> None:
    binary = DIST / exe_name()
    if not binary.exists():
        raise SystemExit(f"build produced no binary at {binary}")
    help_res = subprocess.run([str(binary), "--help"], capture_output=True, text=True)
    if help_res.returncode != 0:
        raise SystemExit(f"smoke test failed: `llama --help` exited {help_res.returncode}\n{help_res.stderr}")
    ver_res = subprocess.run([str(binary), "--version"], capture_output=True, text=True)
    got = ver_res.stdout.strip()
    if ver_res.returncode != 0 or got != version:
        raise SystemExit(
            f"smoke test failed: `llama --version` returned {ver_res.returncode!r} / {got!r}, "
            f"expected {version!r}"
        )
    print(f"smoke test OK: llama --version -> {got}")


# --- macOS code signing + notarization -------------------------------------
# The mac artifact is a BARE onefile Mach-O (not a .app), so it is codesigned
# with the hardened runtime + entitlements and notarized, but CANNOT be stapled
# (stapler only staples bundles/DMGs/installers). Gatekeeper does an online
# notarization check on first run instead. The signed binary must ship UNCHANGED
# after submission — re-signing would change its cdhash and break that check.


def resolve_codesign_identity(explicit: str | None, env: dict, find_identity_output: str) -> str:
    """Developer ID Application identity. Precedence: explicit > env > sole match
    in `security find-identity -v -p codesigning`. Fail on zero / ambiguous."""
    ident = explicit or env.get("LLAMA_CODESIGN_IDENTITY")
    if ident:
        return ident
    names = sorted(set(re.findall(r'"(Developer ID Application:[^"]+)"', find_identity_output)))
    if not names:
        raise SystemExit(
            "no 'Developer ID Application' identity found in the login keychain.\n"
            "  Set LLAMA_CODESIGN_IDENTITY or pass --identity, or build with --skip-sign.\n"
            "  List identities: security find-identity -v -p codesigning"
        )
    if len(names) > 1:
        raise SystemExit(
            f"multiple Developer ID Application identities found: {names}\n"
            "  Disambiguate with LLAMA_CODESIGN_IDENTITY or --identity."
        )
    return names[0]


def _team_from_identity(identity: str | None) -> str:
    m = re.search(r"\(([A-Z0-9]+)\)\s*$", identity or "")
    return m.group(1) if m else ""


def resolve_notary_auth(env: dict, profile: str, keychain: str | None,
                        identity: str | None) -> tuple[list[str], str]:
    """notarytool auth args + human description. Precedence: API key >
    Apple-ID+password > keychain profile (pinned with --keychain)."""
    key, key_id, issuer = (env.get("LLAMA_NOTARY_KEY"), env.get("LLAMA_NOTARY_KEY_ID"),
                           env.get("LLAMA_NOTARY_ISSUER"))
    if key and key_id and issuer:
        return (["--key", key, "--key-id", key_id, "--issuer", issuer], f"API key ({key_id})")
    apple_id, password = env.get("LLAMA_NOTARY_APPLE_ID"), env.get("LLAMA_NOTARY_PASSWORD")
    if apple_id and password:
        team = env.get("LLAMA_NOTARY_TEAM_ID") or _team_from_identity(identity)
        if not team:
            raise SystemExit(
                "notary Apple-ID auth needs a team id: set LLAMA_NOTARY_TEAM_ID "
                "(or use a signing identity ending in '(TEAMID)')."
            )
        return (["--apple-id", apple_id, "--password", password, "--team-id", team],
                f"Apple ID ({apple_id}, team {team})")
    args = ["--keychain-profile", profile]
    if keychain:
        args += ["--keychain", str(keychain)]
    return (args, f"keychain profile '{profile}'")


def wants_dedicated_keychain(env: dict) -> bool:
    return bool(env.get("LLAMA_SIGNING_P12"))


def codesign_cmd(binary: Path, identity: str, entitlements: Path) -> list[str]:
    return ["codesign", "--force", "--options", "runtime",
            "--entitlements", str(entitlements), "--sign", identity, str(binary)]


def _user_keychains() -> list[str]:
    out = subprocess.run(["security", "list-keychains", "-d", "user"],
                         capture_output=True, text=True).stdout
    return [ln.strip().strip('"') for ln in out.splitlines() if ln.strip()]


def _setup_signing_keychain(env: dict):
    """Headless codesign: import LLAMA_SIGNING_P12 into a throwaway keychain we
    unlock ourselves (the login keychain's key is unusable from a background
    runner session). Returns a teardown callable."""
    p12 = env["LLAMA_SIGNING_P12"]
    p12_pw = env.get("LLAMA_SIGNING_P12_PASSWORD")
    kc_pw = env.get("LLAMA_SIGNING_KEYCHAIN_PASSWORD")
    if not Path(p12).exists():
        raise SystemExit(f"LLAMA_SIGNING_P12 not found: {p12}")
    if not p12_pw or not kc_pw:
        raise SystemExit("set LLAMA_SIGNING_P12_PASSWORD and LLAMA_SIGNING_KEYCHAIN_PASSWORD "
                         "alongside LLAMA_SIGNING_P12")
    tmp = str(Path(tempfile.gettempdir()) / f"llama-signing-{os.getpid()}.keychain-db")
    orig = _user_keychains()
    subprocess.run(["security", "create-keychain", "-p", kc_pw, tmp], check=True)
    subprocess.run(["security", "set-keychain-settings", tmp], check=True)
    subprocess.run(["security", "unlock-keychain", "-p", kc_pw, tmp], check=True)
    subprocess.run(["security", "import", p12, "-k", tmp, "-P", p12_pw,
                    "-T", "/usr/bin/codesign"], check=True)
    subprocess.run(["security", "set-key-partition-list", "-S",
                    "apple-tool:,apple:,codesign:", "-s", "-k", kc_pw, tmp], check=True)
    subprocess.run(["security", "list-keychains", "-d", "user", "-s", tmp, *orig], check=True)

    def teardown():
        subprocess.run(["security", "list-keychains", "-d", "user", "-s", *orig], check=False)
        subprocess.run(["security", "delete-keychain", tmp], check=False)

    return teardown


def macos_sign(binary: Path, identity: str | None, notary_profile: str,
               env: dict | None = None) -> None:
    env = os.environ if env is None else env
    if not ENTITLEMENTS.exists():
        raise SystemExit(f"entitlements file missing: {ENTITLEMENTS}")
    found = subprocess.run(["security", "find-identity", "-v", "-p", "codesigning"],
                           capture_output=True, text=True).stdout
    ident = resolve_codesign_identity(identity, env, found)
    teardown = _setup_signing_keychain(env) if wants_dedicated_keychain(env) else None
    try:
        print(f"codesign: {ident}")
        subprocess.run(codesign_cmd(binary, ident, ENTITLEMENTS), check=True)
        subprocess.run(["codesign", "--verify", "--strict", "--verbose=2", str(binary)], check=True)

        if "LLAMA_NOTARY_KEYCHAIN" in env:
            keychain = env["LLAMA_NOTARY_KEYCHAIN"] or None
        else:
            keychain = str(Path.home() / "Library" / "Keychains" / "login.keychain-db")
        auth, kind = resolve_notary_auth(env, notary_profile, keychain, ident)
        print(f"notarize: {kind}")
        zip_path = binary.with_suffix(".notarize.zip")
        if zip_path.exists():
            zip_path.unlink()
        try:
            subprocess.run(["ditto", "-c", "-k", str(binary), str(zip_path)], check=True)
            subprocess.run(["xcrun", "notarytool", "submit", str(zip_path), *auth, "--wait"], check=True)
        finally:
            if zip_path.exists():
                zip_path.unlink()
        # Bare Mach-O: no stapling. Best-effort Gatekeeper assessment (don't fail on it).
        subprocess.run(["spctl", "--assess", "--type", "exec", "--verbose=2", str(binary)], check=False)
        print(f"signed + notarized: {binary} (not stapled — Gatekeeper checks online on first run)")
    finally:
        if teardown:
            teardown()


# --- Windows Authenticode signing (Azure Trusted Signing) ------------------
# One `signtool sign` call on the onefile .exe, using the x64 signtool.exe +
# Azure.CodeSigning.Dlib.dll driven by packaging/metadata.json. Azure auth is
# the machine-side `az` login on the runner — no CI secret.


def check_metadata_not_placeholder(text: str) -> None:
    if "<my-account-name>" in text or "<my-profile-name>" in text:
        raise SystemExit(
            "packaging/metadata.json still has placeholder values — set "
            "CodeSigningAccountName / CertificateProfileName before signing."
        )


def discover_signtool(fixed_path: Path, kits_bin_dir: Path) -> Path:
    if fixed_path.exists():
        return fixed_path
    cands = sorted((p for p in kits_bin_dir.glob("**/x64/signtool.exe")),
                   key=str, reverse=True)
    if cands:
        return cands[0]
    raise SystemExit(
        f"no x64 signtool.exe found under {kits_bin_dir}. "
        "Install the Windows SDK Signing Tools."
    )


def signtool_sign_cmd(signtool: Path, dlib: Path, metadata: Path,
                      timestamp: str, digest: str, files: list) -> list[str]:
    return [str(signtool), "sign", "/v", "/debug", "/fd", digest,
            "/tr", timestamp, "/td", digest, "/dlib", str(dlib),
            "/dmdf", str(metadata), *[str(f) for f in files]]


def ensure_az_on_path(env: dict, candidate_dirs=AZ_WBIN_DIRS, which=shutil.which) -> dict:
    """The dlib's credential shells out to `az`; a runner whose PATH predates the
    az install won't find it. Prepend az's wbin dir for the sign subprocess."""
    if which("az", path=env.get("PATH")):
        return env
    for d in candidate_dirs:
        if (Path(d) / "az.cmd").exists():
            return {**env, "PATH": d + os.pathsep + env.get("PATH", "")}
    return env


def windows_sign(binary: Path, env: dict | None = None) -> None:
    env = dict(os.environ if env is None else env)
    dlib = (Path(env.get("LOCALAPPDATA", "")) / "Microsoft"
            / "MicrosoftArtifactSigningClientTools" / "Azure.CodeSigning.Dlib.dll")
    if not dlib.exists():
        raise SystemExit(f"Azure.CodeSigning.Dlib.dll not found at {dlib}. "
                         "Is ArtifactSigningClientTools installed?")
    if not METADATA.exists():
        raise SystemExit(f"signing metadata missing: {METADATA}")
    check_metadata_not_placeholder(METADATA.read_text(encoding="utf-8"))
    signtool = discover_signtool(SIGNTOOL_FIXED, SIGNTOOL_KITS_BIN)
    env = ensure_az_on_path(env)
    print(f"signtool: {signtool}")
    subprocess.run(signtool_sign_cmd(signtool, dlib, METADATA, TIMESTAMP_URL,
                                     FILE_DIGEST, [binary]), check=True, env=env)
    verify = subprocess.run([str(signtool), "verify", "/pa", "/q", str(binary)])
    if verify.returncode != 0:
        raise SystemExit(f"signtool verify returned {verify.returncode} for {binary}: "
                         "signing could not be verified.")
    print(f"signed + verified: {binary}")


def package(version: str) -> Path:
    DIST_RELEASE.mkdir(parents=True, exist_ok=True)
    stem = f"llama-{version}-{os_slug()}-{arch_slug()}"
    # Stage the single binary in its own dir so the archive has a flat layout.
    stage = DIST_RELEASE / stem
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    shutil.copy2(DIST / exe_name(), stage / exe_name())
    fmt = "zip" if sys.platform == "win32" else "gztar"
    archive = shutil.make_archive(str(DIST_RELEASE / stem), fmt, root_dir=stage)
    shutil.rmtree(stage)
    print(f"packaged: {archive}")
    return Path(archive)


def _print_sign_plan(args) -> None:
    if args.skip_sign:
        print("  sign: SKIPPED (--skip-sign)")
        return
    if sys.platform == "darwin":
        print("  sign: codesign --options runtime --entitlements packaging/llama.entitlements")
        print("  notarize: xcrun notarytool submit --wait  (no stapling — online check on first run)")
    elif sys.platform == "win32":
        print("  sign: signtool sign /dlib Azure.CodeSigning.Dlib /dmdf packaging/metadata.json")
    else:
        print("  sign: n/a (linux)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-sign", action="store_true",
                    help="produce an unsigned build (local/dev; the release workflow never passes this)")
    ap.add_argument("--identity",
                    help="macOS Developer ID Application identity "
                         "(default: auto-detect / LLAMA_CODESIGN_IDENTITY)")
    ap.add_argument("--notary-profile", default=os.environ.get("LLAMA_NOTARY_PROFILE", "litcat-notary"),
                    help="notarytool keychain profile (default litcat-notary / LLAMA_NOTARY_PROFILE)")
    args = ap.parse_args()

    ext = "zip" if sys.platform == "win32" else "tar.gz"
    planned = f"dist-release/llama-{args.version}-{os_slug()}-{arch_slug()}.{ext}"
    if args.dry_run:
        print(f"dry-run: would build and package {planned}")
        _print_sign_plan(args)
        return

    write_version_file(args.version)
    run_pyinstaller(args.version)
    smoke_test(args.version)
    if not args.skip_sign:
        binary = DIST / exe_name()
        if sys.platform == "darwin":
            macos_sign(binary, args.identity, args.notary_profile)
        elif sys.platform == "win32":
            windows_sign(binary)
    package(args.version)


if __name__ == "__main__":
    main()
