#!/usr/bin/env python3
"""Build a self-contained `llama` binary and package it as a release archive.

Usage:
    python packaging/build.py --version 1.2.3 [--dry-run]

Runs on macOS, Linux, and Windows. PyInstaller does not cross-compile, so this
builds only for the host's OS/arch. Output: dist-release/llama-<ver>-<os>-<arch>.<ext>
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SPEC = PROJECT_ROOT / "packaging" / "llama.spec"
DIST = PROJECT_ROOT / "dist"
DIST_RELEASE = PROJECT_ROOT / "dist-release"
VERSION_FILE = PROJECT_ROOT / "src" / "llama" / "_version.py"


def os_slug() -> str:
    if sys.platform == "darwin":
        return "macos"
    if sys.platform.startswith("linux"):
        return "linux"
    if sys.platform == "win32":
        return "windows"
    raise SystemExit(f"unsupported platform: {sys.platform}")


def arch_slug() -> str:
    m = platform.machine().lower()
    if m in ("x86_64", "amd64"):
        return "x86_64"
    if m in ("arm64", "aarch64"):
        return "arm64"
    raise SystemExit(f"unsupported arch: {platform.machine()}")


def exe_name() -> str:
    return "llama.exe" if sys.platform == "win32" else "llama"


def write_version_file(version: str) -> None:
    VERSION_FILE.write_text(
        f'"""Generated by packaging/build.py — do not edit or commit."""\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


def run_pyinstaller(version: str) -> None:
    env = {**os.environ, "LLAMA_VERSION": version}
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", str(SPEC), "--clean", "--noconfirm"],
        cwd=PROJECT_ROOT,
        env=env,
        check=True,
    )


def smoke_test(version: str) -> None:
    binary = DIST / exe_name()
    if not binary.exists():
        raise SystemExit(f"build produced no binary at {binary}")
    help_res = subprocess.run([str(binary), "--help"], capture_output=True, text=True)
    if help_res.returncode != 0:
        raise SystemExit(f"smoke test failed: `llama --help` exited {help_res.returncode}\n{help_res.stderr}")
    ver_res = subprocess.run([str(binary), "--version"], capture_output=True, text=True)
    got = ver_res.stdout.strip()
    if ver_res.returncode != 0 or got != version:
        raise SystemExit(
            f"smoke test failed: `llama --version` returned {ver_res.returncode!r} / {got!r}, "
            f"expected {version!r}"
        )
    print(f"smoke test OK: llama --version -> {got}")


def package(version: str) -> Path:
    DIST_RELEASE.mkdir(parents=True, exist_ok=True)
    stem = f"llama-{version}-{os_slug()}-{arch_slug()}"
    # Stage the single binary in its own dir so the archive has a flat layout.
    stage = DIST_RELEASE / stem
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    shutil.copy2(DIST / exe_name(), stage / exe_name())
    fmt = "zip" if sys.platform == "win32" else "gztar"
    archive = shutil.make_archive(str(DIST_RELEASE / stem), fmt, root_dir=stage)
    shutil.rmtree(stage)
    print(f"packaged: {archive}")
    return Path(archive)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    ext = "zip" if sys.platform == "win32" else "tar.gz"
    planned = f"dist-release/llama-{args.version}-{os_slug()}-{arch_slug()}.{ext}"
    if args.dry_run:
        print(f"dry-run: would build and package {planned}")
        return

    write_version_file(args.version)
    run_pyinstaller(args.version)
    smoke_test(args.version)
    package(args.version)


if __name__ == "__main__":
    main()
